services:
  db:
    image: postgres:16
    container_name: arroyo_postgres_db
    restart: always
    environment:
      # Read from .env or keep hardcoded for this example
      POSTGRES_DB: ${POSTGRES_DB:-arroyo}
      POSTGRES_USER: ${POSTGRES_USER:-arroyo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-arroyo}
    ports:
      - "5432:5432"
    volumes:
      - arroyo_postgres_data:/var/lib/postgresql/data
      # Mount the init scripts directory
      - ./postgres-init:/docker-entrypoint-initdb.d
    # Optional but recommended: Add a healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-arroyo} -d ${POSTGRES_DB:-arroyo} && sleep 1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  arroyo_postgres_data:
